### PR TITLE
Dir: Add `open_dir_of` API

### PR DESCRIPTION
**Pull request by cgwalters**
When porting to cap-std for many codebases, I think it will be
a fairly common operation to take an ambient path (which could be
absolute or relative to cwd) and want to access its parent directory.

In particular, in order to use this crate's handy "atomic file replacement"
APIs, one needs to correctly split such a path into a `Dir` instance
and a filename.

### CODE REVIEW

**Comment by cgwalters** [comment]
cc @sunfishcode - does this make sense to you?  Should it live in cap-std?

**Comment by sunfishcode** [comment]
I'm not quite clear on how this would be used in practice. Could you spell out the atomic file replacement use case? It seems like if you have an ambient path to a file and you want to atomically replace another file with it, there should be simpler ways to do that than opening the parent as a `Dir` and then using the `Dir` to do the replace.

**Comment by cgwalters** [comment]
>  Could you spell out the atomic file replacement use case? It seems like if you have an ambient path to a file and you want to atomically replace another file with it, there should be simpler ways to do that than opening the parent as a Dir and then using the Dir to do the replace.

There's two aspects to this.  First, there's the "under the hood" aspect.  I am not aware of a better way to implement atomic file replacement (on Linux) than what we're doing in this codebase in https://github.com/coreos/cap-std-ext/blob/main/src/tempfile.rs

We need the parent directory because we want to create the temporary file in at least the same filesystem so that we can rely on `rename()` being atomic.

Now, the second aspect of this is - should that be the API exposed directly to the user?

I could imagine that we instead have `Dir::replace_file_contents_ambient()` - is that what you're thinking?  But if we do want to go that route, I think it makes sense to build such an API on top of this lower level helper.

**Comment by sunfishcode** [comment]
If I understand correctly, this `replace_file_contents_ambient` API isn't logically a `Dir` API; it's more of an API that uses `Dir` internally. Does that sound right?

The lower-level `open_dir_of` does return a `Dir`, but in that case, my question is whether that's a useful function outside of this atomic-replace kind of use case. It doesn't need any of cap-std's internals, so if the only user is `replace_file_contents_ambient` and similar, then perhaps it could just be part of the implementation of `replace_file_contents_ambient`.

**Comment by cgwalters** [comment]
The current [cap_std::fs docs](https://docs.rs/cap-std/latest/cap_std/fs/index.html) say:

> Instead of [std::fs’s free functions](https://doc.rust-lang.org/std/fs/#functions) and [std::fs::File](https://doc.rust-lang.org/nightly/std/fs/struct.File.html)’s constructors which operate on bare paths, this crate has methods on [Dir](https://docs.rs/cap-std/latest/cap_std/fs/struct.Dir.html) which operate on paths which must be relative to the directory.

But here we really are trying to deal with an ambient file, much like the equivalent of e.g. [std::fs::write](https://doc.rust-lang.org/std/fs/fn.write.html) (except atomic).

> then perhaps it could just be part of the implementation of replace_file_contents_ambient.

The downside I see here is needing to duplicate the relevant APIs with `_ambient` versions; so far there are only two, but I could imagine more.

For example, maybe someone wants to e.g. query the file metadata or remove it before writing a new version.  Today there's `cap_std::fs::File::open_ambient` but not `metadata_ambient` for example.

So I'd argue `open_dir_of` is a general operation.

**Comment by cgwalters** [comment]
Another alternative to this I guess is to just use `std::fs::` for ambient paths, and I should try to stick the "atomic file replacement" helpers in a place they can be shared with a separate crate.  (Or I guess, try to get them into `std`)

**Comment by sunfishcode** [comment]
cap-std isn't meant to be a collection of useful miscellaneous APIs; it's for capability-based APIs. It does have a few "ambient" functions, but their purpose is to support the capability-based APIs.

`replace_file_contents_ambient` is a useful feature, but it isn't a capability-based feature, and doesn't clearly support the capability-based APIs.

cap-std could add a `cap_std::fs::Metadata::from_ambient_path` or so, if someone wanted this. For many use cases though, `std::fs::metadata` is already adequate for that purpose.

All that said, I do now see the value in having an atomic-replace API in the cap-std repo. I don't yet know what form it should take though; options include adding analogs of the `persist` APIs of [tempfile](https://crates.io/crates/tempfile) to cap-tempfile, adding a `cap-atomicwrites` crate as a capability-based version of [atomicwrites](https://crates.io/crates/atomicwrites), or adding a new crate named something like cap-atomic-replace or so, possibly based on the code in cap-std-ext.

I'm specifically thinking this doesn't belong in the existing `cap_std` or `cap_fs_ext` crates, because `cap_std` aims to stay close to Rust's `std` feature set, and `cap_fs_ext` aims to fill in standard-library-like functionality, which admittedly vague, but I'd prefer to avoid making it even more vague. But I am open to adding to expanding the set of crates in the cap-std repo, if needed, to cover atomic-replace.

For `open_dir_of`, it's fine to factor it out into a utility function that could be shared by various atomic-replace features, but with the use cases I know about, it still feels like a fairly specialized feature.

**Comment by cgwalters** [comment]
I guess there's an argument indeed that I should be depending on (and contributing to) a crate like atomicwrites.  But...hmm, I think this actually fits more into tempfile - the non-cap version of which has an API for this too: https://docs.rs/tempfile/latest/tempfile/struct.NamedTempFile.html#method.persist - it's just not as ergonomic because it requires specifying the path twice.  Also, it doesn't use `O_TMPFILE` on Linux; IOW the partially-written file will always have a name, which means on process/system crash it's much more likely that there are leaked temporary files.  (Eventually I hope [AT_LINK_REPLACE appears](https://marc.info/?l=linux-fsdevel&m=158028833007418&w=2) which would close that gap)

I think this use case really is in a grey area between "general filesystem API" and "tempfile" and it definitely touches on capabilities too (implementing this at least internally is really best done in terms of dirfds).  

Where I'm leaning is to add ergonomic atomic file replacement into `cap-tempfile`.  But `cap-atomicwrites` seems OK to me too I guess.

**Comment by cgwalters** [comment]
Closing in favor of https://github.com/bytecodealliance/cap-std/pull/239

**Pull request closed without merging**
